org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Opt out of AGP 9+ new DSL (Flutter plugin not yet compatible)
android.newDsl=false

# Android 仓库镜像
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=

# 阿里云 Maven 镜像
org.gradle.configureondemand=true
org.gradle.caching=true